### ISSUE TITLE
Changes in list endpoints

### ISSUE THREAD

**Issue by EndBug** [dbots-pkg/dbots.js#20]
Lists to update:

- [x] ListMyBots - breaking
- [x] GlennBotList - breaking
- [x] DiscordBotList - breaking

<hr/>
Hey, I've updated the package because ListMyBots has put online a new website, and they've made breaking changes to the API.  
Would you mind checking if everything's ok? Commit: 0d78550880f13703791640f8d30c39351e63d7d3
If so, this requires a new major version.

**Comment by Snazzah** [comment]
It's good.

**Comment by EndBug** [comment]
@Snazzah Ok, I'm working on updating another service too, I'll tell you when I'm done

**Comment by Snazzah** [comment]
There's some breaking changes for `DiscordBotList` aswell
https://docs.discordbotlist.com/bot-statistics

**Comment by EndBug** [comment]
I see that in the docs they changed the bad URL to `https://discordbotlist.com/api/v1` (they added the `v1`), but the old one seems to work just fine. What should we do?
The widget URL method needs to be removed though

**Comment by Snazzah** [comment]
Add on the `v1` and remove the widget function.
The widget is broken and replaced with a JavaScript widget, but I think it is worth removing since we only really document photo widgets.

**Comment by EndBug** [comment]
Fixed by release 4.0.0
