### ISSUE TITLE
5 new Services: DiscordLabs, Blist, TopCord, DiscordListology, DiscordBotsCo

### ISSUE THREAD

**Issue by Snazzah** [dbots-pkg/dbots.js#50]
DiscordLabs
- Website: https://bots.discordlabs.org/
- Docs: https://docs.discordlabs.org/docs/api/api

Blist
- Website: https://blist.xyz/
- Docs: https://blist.xyz/docs/

TopCord
- Website: https://topcord.xyz/
- Docs: https://docs.topcord.xyz/#/API

DiscordListology
- Website: https://discordlistology.com/
- Docs: https://discordlistology.com/developer/documentation (requires login)

DiscordBotsCo
- Website: https://discordbots.co/
- Docs: https://discordbots.co/api

**Comment by EndBug** [comment]
Are you already working on them? If so I won't do anything to avoid merge issues

**Comment by Snazzah** [comment]
I'm not working on it right now, made an issue to support later. You can
create a PR if you want.
