### ISSUE TITLE
TypeScript rewrite

### ISSUE THREAD

**Issue by EndBug** [dbots-pkg/dbots.js#71]
This is an issue meant to track every change and known issue with the TypeScript rewrite, currently living in the [`typescript` branch](https://github.com/dbots-pkg/dbots.js/tree/typescript). 
Directly edit this comment to add changes or known issues.

## Potentially breaking changes 
- `*` - The whole package is now written in TypeScript. The scripts have changed too.
- `*` - JSDoc annotation no longer have types, everything that can be moved to TS should no longer be written in JSDoc
  - `@private` tags can still be used when we want to mark something as "private" for the docs website, but it's not an actual private property
- `*` - In the whole package, internal `module.exports =` exports have been replaced by `default` exports
- `*` - In the whole package, functions and methods no longer return `null` when only `undefined` is documented; if they can return `null` it will be explicitly documented
- `*` - In the whole package, it's preferred to create a dedicated type/interface to document function argument, instead of using an "inline type"
- `index` - Each service class  now has to be accessed via the `dbots.serviceClasses` constant, instead of directly from `dbots` (e.g. `dbots.Arcane` now becomes `dbots.serviceClasses.Arcane`)
- `index` - two functions have been renamed to camelCase (`formatRequest` and `ensurePromise`)
- `Utils/Constants` - In `PostRequestData`, multiple properties are now optional
- `Utils/Constants` - The supported `Poster` events have been renamed
- `Utils/DbotsError` - The exported `Error`, `TypeError`, and `RangeError` classes are now grouped under the `errors` exported constant (e.g. `dbotserror.Error` is now `dbotserror.errors.Error`)
- `Utils/FormatRequest` - In `RequestForm`, multiple properties are now optional
- `Utils/FormatRequest` -  `FormatRequest` no longer supports aliases for some options; the correct option name is enforced by the type of the argument
- `Utils/Util` - added the `AnyObject` type and the `assert` function
- `Interface/ServiceBase` - The `ServiceBase.name` static property is now called `ServiceBase.serviceName`, in order to avoid conflicts with the `Function.name` property
- `Interface/Lists/*` - They all extend `ServiceBase`, and so they all have the previous change
- `Interface/ClientFiller` - circular imports have been removed, the static class method is now a separate function
- `Interface/ClientFiller` - the new function to get client fillers does not support library aliases; the argument now uses the `Library` type
- `Service` has been renamed to `ServiceKey`
- `ServiceBase` has been renamed to `Service`

## Known issues

- ~Typedefs show a "Types" header even when they don't have any (e.g. when they're an interface, and so there's only a "Properties" section) ([img](https://get.snaz.in/2gGeJ95.png))~
- ~Descriptions are not showing up for function parameters ([img1](https://get.snaz.in/3JKrXBk.png), [img2](https://get.snaz.in/AUFXDWD.png))~
- ~Union types don't have type links~
- ~Some built-in types are missing~
- ~`Poster#post` is not showing up in the website~
- ~Lint GH actions workflow is not working~
- ~Viewing the source of typedefs go to `undefined`~
- ~Poster events are missing from their respective methods~
- ~`typeof Class` types show up as `unknown`~
- ~Accessors are not documented~
- ~Optional and Default fields do not show in class constructor param tables ([expected](https://get.snaz.in/2B6aXfr.png), [actual](https://get.snaz.in/6CSkc4E.png))~
- ~default value does not show in PosterOptions (i.e. `useSharding`)~
- ~Tests are missing~

**Comment by Snazzah** [comment]
Are we able to rename `ServiceBase` to `Service` since this is looking like a major change?

**Comment by EndBug** [comment]
Yeah, sure

**Comment by EndBug** [comment]
@Snazzah I was renaming `ServiceBase` to `Service`, but I've seen that we already have a type named like that: https://dbots.js.org/#/docs/main/latest/typedef/Service

Do you still want to rename it? (`ServiceBase` is not that bad after all)

**Comment by Snazzah** [comment]
@EndBug We could rename that to `ServiceKey` since its a more accurate name

**Comment by EndBug** [comment]
@Snazzah Can we drop support for all the library aliases? They're not in the docs, so we might as well enforce the names using a type, and at that point we would just need to use the main name

**Comment by EndBug** [comment]
We could also try to do something similar to how we document services

**Comment by Snazzah** [comment]
@EndBug I'm fine with that, having multiple aliases is unnecessary now that I think about it.

**Comment by EndBug** [comment]
@Snazzah Since we added tests now everything should work as expected.
I've also tested the new package with my bot and it works fine (even though I only use the basic functionalities)
Do you have any other issues or do you want to make some other test with one of your bots? Otherwise, I think I can start merging the branch to master

**Comment by Snazzah** [comment]
@EndBug What botlists/features did you use? I think the project is stable from what I've seen, but I can't test it at the moment.

**Comment by EndBug** [comment]
@Snazzah I'm only using the Poster auto-post to 22 services: 2 of them are being rejected, but I think that doesn't depend on the TS rewrite, it's just something that we can fix later.
I'm not using any library other than djs and I'm not using service methods other than post

**Comment by Snazzah** [comment]
@EndBug That should be good to merge then.
